version: '3'

services:
  pg:
    build: "./docker/pg"
    image: "mortar/pg"
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - "./pg-data/:/data/"
  mortar-server:
    build:
      context: .
      dockerfile: "./docker/mortar-server/Dockerfile"
    image: "mortar/server2"
    restart: always
    depends_on:
      - "pg"
    environment:
      - MORTAR_HTTP_ADDRESS=0.0.0.0
      - MORTAR_HTTP_PORT=5001
      - MORTAR_DB_HOST=pg
      - MORTAR_DB_PORT=5432
      - MORTAR_DB_DATABASE=mortar
      - MORTAR_DB_USER=mortarchangeme
      - MORTAR_DB_PASSWORD=mortarpasswordchangeme
      - MORTAR_REASONER_ADDRESS=reasoner:3030
    ports:
      - "5001:5001"
        # - "2112:2112"
  prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
  cadvisor:
    image: google/cadvisor:latest
    restart: always
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - pg
  reasoner:
    build:
      context: .
      dockerfile: "./docker/reasoner/Dockerfile"
    image: "mortar/reasoner"
    restart: always
    environment:
      - MORTAR_DB_HOST=pg
      - MORTAR_DB_PORT=5432
      - MORTAR_DB_DATABASE=mortar
      - MORTAR_DB_USER=mortarchangeme
      - MORTAR_DB_PASSWORD=mortarpasswordchangeme
    ports:
      - "3030:3030"
    depends_on:
      - pg
      - mortar-server
  jupyter-notebook:
    image: jupyter/scipy-notebook
    restart: always
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token=test-secret --NotebookApp.allow_origin='*'"
