scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: commons-server
  scrape_interval: 5s
  static_configs:
  - targets:
    - commons-server:2112
